apiVersion: apps/v1
kind: Deployment
metadata:
  name: cliente-service-deployment
  labels:
    app: cliente-service-deployment
spec:
  selector:
    matchLabels:
      app: cliente-service-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: cliente-service-deployment
    spec:
      containers:
        - name: cliente-service
          image: diego9028/cliente-server:latest
          ports:
            - containerPort: 8096
          env:
            - name: SERVER_PORT
              value: "0"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_HOST_CLIENTE
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_PORT_CLIENTE
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_NAME_CLIENTE
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_USER_CLIENTE
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_PASSWORD_CLIENTE